[package]
name = "anvil-slash"
version = "0.1.0"
edition = "2021"


[dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net"] }
hyper = { version = "0.14", features = ["server", "http1"] }
serde = { version = "1", features = ["derive"] }
http = "0.2"
serde_json = "1"
ed25519-dalek = "1"
hex = "0.4"
twilight-model = "0.13"
twilight-http = "0.13"
thiserror = "1"
