[package]
name = "anvil-slash"
version = "0.1.0"
edition = "2021"


[dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net"] }
sqlx = { version = "0.6", features = ["runtime-tokio-native-tls", "tls", "mysql", "macros", "offline"] }
axum = "0.6.0-rc.2"
serde_json = "1"
ed25519-dalek = "1"
hex = "0.4"
thiserror = "1"
twilight-model = "0.13"
twilight-http = "0.13"
twilight-util = { version = "0.13", features = ["builder"] }
