[package]
name = "experienced-slash"
version = "0.1.0"
edition = "2021"
authors = ["valkyrie_pilot <valk@randomairborne.dev>"]
description = "A slash command handler for experienced"
repository = "https://github.com/randomairborne/experienced"
readme = "README.txt"
license = "MS-PL"
categories = ["games"]
keywords = ["discord-bot", "mee6"]

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros", "signal"] }
sqlx = { version = "0.6", features = ["runtime-tokio-rustls", "tls", "postgres", "macros", "offline"] }
serde = { version = "1", features = ["derive"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
reqwest = { version = "0.11", features = ["json"] }
tracing = "0.1"
axum = "0.6.2"
serde_json = "1"
ed25519-dalek = "1"
hex = "0.4"
thiserror = "1"
twilight-model = "0.14"
twilight-http = "0.14"
twilight-util = { version = "0.14", features = ["builder"] }
dotenvy = "0.15"
mee6 = "0.0.3"
resvg = "0.28"
tera = "1"
png = "0.17"
