[workspace]
members = [
    "mee6",
    "xpd-slash",
    "xpd-listener",
    "xpd-gateway",
    "xpd-common",
    "xpd-rank-card"
, "xpd-permission-cache"]
resolver = "2"
default-members = ["xpd-gateway"]
