version: "3.9"
services:
  listener:
    image: ghcr.io/randomairborne/experienced-listener:latest
    networks:
      - database
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DATABASE_URL: "mysql://experienced:experienced@database/experienced"

  slash:
    image: ghcr.io/randomairborne/experienced-slash:latest
    ports:
      - "5389:8080"
    networks:
      - database
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DISCORD_PUBKEY: ${DISCORD_PUBKEY}
      WEBSITE_URL: ${WEBSITE_URL}
      DATABASE_URL: "mysql://experienced:experienced@database/experienced"


  database:
    image: mariadb:latest
    command: --init-file /tmp/database.mysql
    volumes:
        - ./database.mysql:/tmp/database.mysql
        - experienced-data:/var/lib/mysql/
    networks:
      - database
    environment:
      MYSQL_ROOT_PASSWORD: root-pw
      MYSQL_DATABASE: experienced
      MYSQL_USER: experienced
      MYSQL_PASSWORD: experienced

networks:
  database: {}

volumes:
  experienced-data: {}
