networks:
  xpd-network:
    external: false

services:
  xpd-gateway:
    image: ghcr.io/randomairborne/xpd-gateway:latest
    restart: unless-stopped
    networks:
      - xpd-network
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
      - postgres

  redis:
    image: redis
    restart: unless-stopped
    networks:
      - xpd-network

  postgres:
    image: postgres:16-alpine3.19
    restart: unless-stopped
    networks:
      - xpd-network
    env_file:
      - .env
    environment:
      - POSTGRES_USER=xpd
      - POSTGRES_DB=xpd
    volumes:
      - ./postgres:/var/lib/postgresql/data
