[package]
name = "anvil-listener"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3"
rand = "0.8"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync"] }
twilight-gateway = { default-features = false, features = ["native"], version = "0.13" }
sqlx = { version = "0.6", features = ["runtime-tokio-native-tls", "tls", "mysql"] }

