# fly.toml file generated for xpd-listener on 2023-01-10T16:33:07Z

app = "xpd-listener"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "ghcr.io/randomairborne/experienced-listener:latest"

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
