[package]
name = "xpd-common"
version = "0.0.6"
edition = "2021"
description = "Common structures for the experienced discord bot"
repository = "https://github.com/randomairborne/experienced"
license = "EUPL-1.2"
readme = "README.txt"
categories = ["games"]
keywords = ["discord-bot", "mee6"]

[dependencies]
twilight-model = "0.15"