name: Static checks
on:
  push:
  pull_request:
  workflow_dispatch:

env:
  DATABASE_URL: "mysql://root:root@localhost/testing"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Start MySQL
        run: sudo /etc/init.d/mysql start

      - name: Create MySQL test database
        run: sudo mysql -e 'CREATE DATABASE testing;' --user=root --password=root
          
      - name: Check out code into the proper directory
        uses: actions/checkout@v2

      - name: Run database migrations
        run: mysql --user=root --password=root testing < database.mysql

      - name: Install cargo
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
          
      - name: Check formatting
        run: cargo fmt --check

      - name: Check build
        run: cargo clippy

