name: Static checks
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the proper directory
        uses: actions/checkout@v2

      - name: Install cargo
        uses: actions-rs/toolchain@v1

      - name: Check formatting
        run: cargo fmt --check

      - name: Check build
        run: cargo clippy 

