name: CI
on:
  push:

jobs:
  listener:
    runs-on: ubuntu-latest

    steps:
      - name: Correct env
        run:
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Check out code into the proper directory
        uses: actions/checkout@v2

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container
        uses: docker/build-push-action@v2
        with:
          context: ./listener/
          push: true
          tags: ghcr.io/${{ env.REPO }}-listener:latest
          platforms: linux/amd64,linux/arm64


  slash:
    runs-on: ubuntu-latest

    steps:
      - name: Correct env
        run:
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Check out code into the proper directory
        uses: actions/checkout@v2

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container
        uses: docker/build-push-action@v2
        with:
          context: ./slash/
          push: true
          tags: ghcr.io/${{ env.REPO }}-slash:latest
          platforms: linux/amd64,linux/arm64
