name: PR check
on:
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  cargo-tests:
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:latest
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Check out code into the proper directory
        uses: actions/checkout@v4

      - name: Install cargo
        uses: dtolnay/rust-toolchain@nightly

      - name: Run tests
        run: cargo test --all

  rust-clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the proper directory
        uses: actions/checkout@v4

      - name: Install cargo
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy

      - name: Install NPM deps
        run: cargo +nightly clippy --all -- -D warnings
        env:
          SQLX_OFFLINE: true

  rust-fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the proper directory
        uses: actions/checkout@v4

      - name: Install cargo
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - name: Install NPM deps
        run: cargo +nightly fmt --check --all

  js-fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the proper directory
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4

      - name: Install NPM deps
        run: npm install
        shell: bash

      - name: Check web formatting
        run: npm run prettier-check
