name: PR check
on:
  pull_request:
  workflow_dispatch:
  workflow_call:

env:
  DATABASE_URL: "mysql://root:root@localhost/experienced"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Start MySQL
        run: sudo /etc/init.d/mysql start

      - name: Create MySQL test database
        run: sudo mysql -e 'CREATE DATABASE experienced;' --user=root --password=root

      - name: Check out code into the proper directory
        uses: actions/checkout@v3

      - name: Run database migrations
        run: mysql --user=root --password=root < ./migrations/init.sql

      - name: Install cargo
        uses: dtolnay/rust-toolchain@master
        with:
          components: rustfmt, clippy
 
      - name: Cache rust
        uses: Swatinem/rust-cache@v2

      - name: Check formatting
        run: cargo fmt --check

      - name: Check build
        run: cargo clippy

      - name: Run tests
        run: cargo test
