name: PR check
on:
  pull_request:
  workflow_dispatch:
  workflow_call:

env:
  SQLX_OFFLINE: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the proper directory
        uses: actions/checkout@v4

      - name: Install cargo
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Check Rust formatting
        run: cargo fmt --check

      - name: Install prettier
        run: npm install

      - name: Check web formatting
        run: npm run prettier-check

      - name: Check build
        run: cargo clippy -- -D warnings

      - name: Run tests
        run: cargo test --all
