name: PR check
on:
  pull_request:
  workflow_dispatch:
  workflow_call:

env:
  SQLX_OFFLINE: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the proper directory
        uses: actions/checkout@v4

      - name: Install cargo
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Install NPM deps
        run: npm install

      - name: Run verifications
        run: ./ci/lint.sh
        shell: bash
