name: CI
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DATABASE_URL: "mysql://root:root@localhost/experienced"

jobs:
  check:
    uses: ./.github/workflows/check.yml
  deploy:
    runs-on: ubuntu-latest
    needs: [check]
    strategy:
      fail-fast: true
      matrix:
        side: [listener, slash]
    steps:
      - name: Correct env
        run:
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Check out code into the proper directory
        uses: actions/checkout@v3

      - name: Start MySQL
        run: sudo /etc/init.d/mysql start

      - name: Create MySQL test database
        run: sudo mysql -e 'CREATE DATABASE experienced;' --user=root --password=root

      - name: Run database migrations
        run: mysql --user=root --password=root < ./migrations/init.sql

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container
        uses: docker/build-push-action@v3
        with:
          context: ./${{ matrix.side }}/
          push: true
          tags: ghcr.io/${{ env.REPO }}-${{ matrix.side }}:latest
          platforms: linux/amd64
          network: host
          build-args: |
            database_url=${{ env.DATABASE_URL }}

