name: CI
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  SQLX_OFFLINE: true

jobs:
  check:
    uses: ./.github/workflows/check.yml
  deploy:
    runs-on: ubuntu-latest
    needs: [check]
    strategy:
      fail-fast: true
      matrix:
        side: [listener, slash]
    steps:
      - name: Correct env
        run:
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Check out code into the proper directory
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container
        uses: docker/build-push-action@v3
        with:
          context: ./${{ matrix.side }}/
          push: true
          tags: ghcr.io/${{ env.REPO }}-${{ matrix.side }}:latest
          platforms: linux/amd64

